### ISSUE TITLE
new containers DB error when starting up

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#17]
A couple of values sanitized below for privacy reasons but they match in the real compose file.

```
  exbin:
    image: m1dnight/exbin:latest
    container_name: exbin
    labels:
      - traefik.enable=true
      - traefik.http.routers.exbin.rule=Host(`paste.123.123`)
      - traefik.http.routers.exbin.entrypoints=websecure
      - traefik.http.routers.exbin.tls.certresolver=cloudflare
      - traefik.http.services.exbin.loadbalancer.server.port=4001
    environment:
      - TCP_PORT=9999
      - TCP_IP=0.0.0.0
      - HTTP_PORT=4001
      - DB_NAME=123
      - DB_PASS=123
      - DB_USER=123
      - MAX_BYTES=5242880
      - EXTERNAL_URL=paste.123.123
      - TZ=America/Seattle
    depends_on:
      - exbin_postgres
    restart: unless-stopped
  exbin_postgres:
    image: postgres:10-alpine
    container_name: exbin_postgres
    volumes:
      - /home/ironicbadger/appdata/exbin/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=123
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=123
    restart: unless-stopped
 ```

Error received is below:

```
03:23:47.932 [error] Postgrex.Protocol (#PID<0.273.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

03:23:48.673 [error] Postgrex.Protocol (#PID<0.274.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

03:23:48.957 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :exbin, ExBin.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2974ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (albeit it increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:836: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:639: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:473: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:388: Ecto.Migrator.run/4
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (ecto_sql 3.6.0) lib/mix/tasks/ecto.migrate.ex:133: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
03:23:50.567 [info] Application exbin exited: ExBin.Application.start(:normal, []) returned an error: shutdown: failed to start child: ExBinWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (RuntimeError) expected the PORT environment variable to be set
            (exbin 0.0.1) lib/exbin_web/endpoint.ex:55: ExBinWeb.Endpoint.init/2
            (phoenix 1.5.8) lib/phoenix/endpoint/supervisor.ex:68: Phoenix.Endpoint.Supervisor.init/1
            (stdlib 3.14) supervisor.erl:301: :supervisor.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application exbin: ExBin.Application.start(:normal, []) returned an error: shutdown: failed to start child: ExBinWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (RuntimeError) expected the PORT environment variable to be set
            (exbin 0.0.1) lib/exbin_web/endpoint.ex:55: ExBinWeb.Endpoint.init/2
            (phoenix 1.5.8) lib/phoenix/endpoint/supervisor.ex:68: Phoenix.Endpoint.Supervisor.init/1
            (stdlib 3.14) supervisor.erl:301: :supervisor.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

03:23:56.439 [error] GenServer #PID<0.273.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

03:23:56.463 [error] GenServer #PID<0.279.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for ExBin.Repo couldn't be created: killed
```
